<?xml version="1.0" encoding="UTF-8"?>
<class-diagram version="1.2.4" icons="true" always-add-relationships="false" generalizations="true" realizations="true" 
  associations="true" dependencies="false" nesting-relationships="true" router="FAN">  
  <class id="1" language="java" name="classes.PizzaFactoryStrasbourg" project="TZMER" 
    file="/TZMER/src/classes/PizzaFactoryStrasbourg.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="160" x="1318" y="498"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="2" language="java" name="classes.PizzeriaBrest" project="TZMER" 
    file="/TZMER/src/classes/PizzeriaBrest.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="143" x="1033" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="3" language="java" name="classes.Pizza" project="TZMER" file="/TZMER/src/classes/Pizza.java" binary="false" 
    corner="BOTTOM_RIGHT">    
    <position height="243" width="125" x="501" y="76"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="4" language="java" name="classes.PizzaTestDrive" project="TZMER" 
    file="/TZMER/src/classes/PizzaTestDrive.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="113" x="728" y="76"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="5" language="java" name="classes.PizzaPoivronStyleStrasbourg" project="TZMER" 
    file="/TZMER/src/classes/PizzaPoivronStyleStrasbourg.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="189" x="183" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="6" language="java" name="classes.PizzaPoivronStyleBrest" project="TZMER" 
    file="/TZMER/src/classes/PizzaPoivronStyleBrest.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="156" x="412" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="7" language="java" name="classes.Pizzeria" project="TZMER" file="/TZMER/src/classes/Pizzeria.java" 
    binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="148" x="1221" y="76"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="8" language="java" name="classes.PizzaCheeseStyleBrest" project="TZMER" 
    file="/TZMER/src/classes/PizzaCheeseStyleBrest.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="156" x="608" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="9" language="java" name="classes.PizzaFactory" project="TZMER" file="/TZMER/src/classes/PizzaFactory.java" 
    binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="153" x="1216" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="10" language="java" name="classes.PizzeriaFactory" project="TZMER" 
    file="/TZMER/src/classes/PizzeriaFactory.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="117" width="168" x="942" y="76"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="11" language="java" name="classes.PizzaCheeseStyleStrasbourg" project="TZMER" 
    file="/TZMER/src/classes/PizzaCheeseStyleStrasbourg.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="189" x="804" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="12" language="java" name="classes.PizzaFactoryBrest" project="TZMER" 
    file="/TZMER/src/classes/PizzaFactoryBrest.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="148" x="1120" y="498"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <class id="13" language="java" name="classes.PizzeriaStrasbourg" project="TZMER" 
    file="/TZMER/src/classes/PizzeriaStrasbourg.java" binary="false" corner="BOTTOM_RIGHT">    
    <position height="99" width="143" x="1409" y="359"/>    
    <display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
      sort-features="false" accessors="true" visibility="true">      
      <attributes public="true" package="true" protected="true" private="true" static="true"/>      
      <operations public="true" package="true" protected="true" private="true" static="true"/>    
    </display>  
  </class>  
  <generalization id="14">    
    <end type="SOURCE" refId="6"/>    
    <end type="TARGET" refId="3"/>  
  </generalization>  
  <generalization id="15">    
    <end type="SOURCE" refId="8"/>    
    <end type="TARGET" refId="3"/>  
  </generalization>  
  <generalization id="16">    
    <end type="SOURCE" refId="12"/>    
    <end type="TARGET" refId="9"/>  
  </generalization>  
  <generalization id="17">    
    <end type="SOURCE" refId="13"/>    
    <end type="TARGET" refId="7"/>  
  </generalization>  
  <generalization id="18">    
    <end type="SOURCE" refId="11"/>    
    <end type="TARGET" refId="3"/>  
  </generalization>  
  <association id="19">    
    <end type="SOURCE" refId="1" navigable="false">      
      <attribute id="20" name="uniqueInstance"/>      
      <multiplicity id="21" minimum="0" maximum="1"/>    
    </end>    
    <end type="TARGET" refId="1" navigable="true"/>    
    <display labels="true" multiplicity="true"/>  
  </association>  
  <generalization id="22">    
    <end type="SOURCE" refId="1"/>    
    <end type="TARGET" refId="9"/>  
  </generalization>  
  <association id="23">    
    <end type="SOURCE" refId="2" navigable="false">      
      <attribute id="24" name="fabrique"/>      
      <multiplicity id="25" minimum="0" maximum="1"/>    
    </end>    
    <end type="TARGET" refId="12" navigable="true"/>    
    <display labels="true" multiplicity="true"/>  
  </association>  
  <association id="26">    
    <end type="SOURCE" refId="10" navigable="false">      
      <attribute id="27" name="uniqueInstance"/>      
      <multiplicity id="28" minimum="0" maximum="1"/>    
    </end>    
    <end type="TARGET" refId="10" navigable="true"/>    
    <display labels="true" multiplicity="true"/>  
  </association>  
  <association id="29">    
    <end type="SOURCE" refId="13" navigable="false">      
      <attribute id="30" name="fabrique"/>      
      <multiplicity id="31" minimum="0" maximum="1"/>    
    </end>    
    <end type="TARGET" refId="1" navigable="true"/>    
    <display labels="true" multiplicity="true"/>  
  </association>  
  <generalization id="32">    
    <end type="SOURCE" refId="5"/>    
    <end type="TARGET" refId="3"/>  
  </generalization>  
  <generalization id="33">    
    <end type="SOURCE" refId="2"/>    
    <end type="TARGET" refId="7"/>  
  </generalization>  
  <association id="34">    
    <end type="SOURCE" refId="12" navigable="false">      
      <attribute id="35" name="uniqueInstance"/>      
      <multiplicity id="36" minimum="0" maximum="1"/>    
    </end>    
    <end type="TARGET" refId="12" navigable="true"/>    
    <display labels="true" multiplicity="true"/>  
  </association>  
  <classifier-display autosize="true" stereotype="true" package="true" initial-value="false" signature="true" 
    sort-features="false" accessors="true" visibility="true">    
    <attributes public="true" package="true" protected="true" private="true" static="true"/>    
    <operations public="true" package="true" protected="true" private="true" static="true"/>  
  </classifier-display>  
  <association-display labels="true" multiplicity="true"/>
</class-diagram>